mode = "light"

accent = "#b6009d"
selection = "#edbfe1"
muted = "#b79e9a"

background = "#fcf5f4"
dark_background = "#f7e7e4"
darker_background = "#eadad7"
lighter_background = "#f2deda"

foreground = "#35201c"
dark_foreground = "#816c68"
light_foreground = "#57423e"
bright_foreground = "#200e0c"

hyprland_active_border = "rgba(916f00ee) rgba(b6009dee) 45deg"
hyprland_inactive_border = "rgba(b79e9aaa)"

red = "#ba0427"
yellow = "#998b09"
orange = "#aa6100"
green = "#af5408"
cyan = "#916f00"
blue = "#925008"
magenta = "#b6009d"
brown = "#663a00"

bright_red = "#99001d"
bright_yellow = "#82760c"
bright_green = "#924401"
bright_cyan = "#785c03"
bright_blue = "#774005"
bright_magenta = "#960081"
