mode = "light"

accent = "#d40729"
selection = "#eac5c4"
muted = "#99aa99"

background = "#f0faf0"
dark_background = "#e4efe4"
darker_background = "#d7e1d7"
lighter_background = "#dae7da"

foreground = "#1c2b1c"
dark_foreground = "#687668"
light_foreground = "#3e4c3e"
bright_foreground = "#0b170b"

hyprland_active_border = "rgba(008b57ee) rgba(d40729ee) 45deg"
hyprland_inactive_border = "rgba(99aa99aa)"

red = "#c53900"
yellow = "#a38b09"
orange = "#b26c00"
green = "#098e00"
cyan = "#008b57"
blue = "#077558"
magenta = "#d40729"
brown = "#6b4100"

bright_red = "#a42e00"
bright_yellow = "#8b7705"
bright_green = "#077600"
bright_cyan = "#087348"
bright_blue = "#045e46"
bright_magenta = "#b00721"
