mode = "light"

accent = "#ba12ad"
selection = "#f0c2e0"
muted = "#b5a094"

background = "#fff4ef"
dark_background = "#f6e8e1"
darker_background = "#e9dbd4"
lighter_background = "#f1dfd5"

foreground = "#342117"
dark_foreground = "#806d63"
light_foreground = "#554339"
bright_foreground = "#1f1007"

hyprland_active_border = "rgba(a7610cee) rgba(ba12adee) 45deg"
hyprland_inactive_border = "rgba(b5a094aa)"

red = "#d40728"
yellow = "#ab8704"
orange = "#bd6400"
green = "#008e14"
cyan = "#a7610c"
blue = "#3d44e8"
magenta = "#ba12ad"
brown = "#713c00"

bright_red = "#b1051f"
bright_yellow = "#927300"
bright_green = "#00760f"
bright_cyan = "#8c4f02"
bright_blue = "#3020d6"
bright_magenta = "#9c0091"
