mode = "light"

accent = "#bb00b1"
selection = "#eac1e8"
muted = "#aaa2a4"

background = "#f7f7f7"
dark_background = "#ebebeb"
darker_background = "#dedede"
lighter_background = "#e3e3e3"

foreground = "#2b2426"
dark_foreground = "#776f71"
light_foreground = "#4d4647"
bright_foreground = "#181214"

hyprland_active_border = "rgba(018589ee) rgba(bb00b1ee) 45deg"
hyprland_inactive_border = "rgba(aaa2a4aa)"

red = "#d60015"
yellow = "#94920f"
orange = "#b16e03"
green = "#078e00"
cyan = "#018589"
blue = "#025bcc"
magenta = "#bb00b1"
brown = "#6a4202"

bright_red = "#b20010"
bright_yellow = "#7e7c09"
bright_green = "#057600"
bright_cyan = "#0a6e72"
bright_blue = "#0049a8"
bright_magenta = "#9b0293"
