mode = "light"

accent = "#c4085e"
selection = "#f0c1d3"
muted = "#b79e9b"

background = "#fcf5f4"
dark_background = "#f7e7e5"
darker_background = "#eadad8"
lighter_background = "#f2dddb"

foreground = "#35201e"
dark_foreground = "#816c69"
light_foreground = "#574240"
bright_foreground = "#200e0d"

hyprland_active_border = "rgba(c24700ee) rgba(c4085eee) 45deg"
hyprland_inactive_border = "rgba(b79e9baa)"

red = "#ba0428"
yellow = "#c3730d"
orange = "#c14b08"
green = "#d20049"
cyan = "#c24700"
blue = "#ac3300"
magenta = "#c4085e"
brown = "#742d05"

bright_red = "#98011f"
bright_yellow = "#a76100"
bright_green = "#af003b"
bright_cyan = "#a23a00"
bright_blue = "#8d2700"
bright_magenta = "#a2044c"
