mode = "light"

accent = "#a64b50"
selection = "#e9d0ce"
muted = "#b0a19a"

background = "#fcf5f1"
dark_background = "#f0eae6"
darker_background = "#e3dcd9"
lighter_background = "#eae1dc"

foreground = "#2f231d"
dark_foreground = "#7b6f68"
light_foreground = "#51453e"
bright_foreground = "#1b110c"

hyprland_active_border = "rgba(a3640fee) rgba(a64b50ee) 45deg"
hyprland_inactive_border = "rgba(b0a19aaa)"

red = "#9c4534"
yellow = "#b17e22"
orange = "#ab6025"
green = "#8f6b0a"
cyan = "#a3640f"
blue = "#99491e"
magenta = "#a64b50"
brown = "#673a16"

bright_red = "#872e1d"
bright_yellow = "#9a6a04"
bright_green = "#775806"
bright_cyan = "#885208"
bright_blue = "#833500"
bright_magenta = "#91343c"
