mode = "light"

accent = "#c50092"
selection = "#eebfe0"
muted = "#ada1a4"

background = "#faf5f6"
dark_background = "#eeeaeb"
darker_background = "#e1ddde"
lighter_background = "#e6e1e3"

foreground = "#2d2326"
dark_foreground = "#796e71"
light_foreground = "#4f4447"
bright_foreground = "#1a1113"

hyprland_active_border = "rgba(02848dee) rgba(c50092ee) 45deg"
hyprland_inactive_border = "rgba(ada1a4aa)"

red = "#d60012"
yellow = "#a38b08"
orange = "#b76900"
green = "#668008"
cyan = "#02848d"
blue = "#133eff"
magenta = "#c50092"
brown = "#6e3f00"

bright_red = "#b2020e"
bright_yellow = "#8b7609"
bright_green = "#546b01"
bright_cyan = "#0e6d74"
bright_blue = "#0c00ed"
bright_magenta = "#a40079"
