mode = "light"

accent = "#bc2c4f"
selection = "#eccace"
muted = "#aca399"

background = "#faf6f2"
dark_background = "#eeeae6"
darker_background = "#e1ddd9"
lighter_background = "#e7e2dd"

foreground = "#2d251c"
dark_foreground = "#787067"
light_foreground = "#4e463e"
bright_foreground = "#19120b"

hyprland_active_border = "rgba(a95f00ee) rgba(bc2c4fee) 45deg"
hyprland_inactive_border = "rgba(aca399aa)"

red = "#b3241f"
yellow = "#b77b0f"
orange = "#b65707"
green = "#8c6d08"
cyan = "#a95f00"
blue = "#0a6e88"
magenta = "#bc2c4f"
brown = "#6d3404"

bright_red = "#990309"
bright_yellow = "#9d6800"
bright_green = "#755900"
bright_cyan = "#8d4e00"
bright_blue = "#01596f"
bright_magenta = "#a5003b"
