mode = "light"

accent = "#a459a6"
selection = "#e3d0eb"
muted = "#a7a1b5"

background = "#f5f1fe"
dark_background = "#eae5f5"
darker_background = "#ddd8e8"
lighter_background = "#e2dcf0"

foreground = "#292237"
dark_foreground = "#746e81"
light_foreground = "#4a4458"
bright_foreground = "#16111f"

hyprland_active_border = "rgba(0e919aee) rgba(a459a6ee) 45deg"
hyprland_inactive_border = "rgba(a7a1b5aa)"

red = "#b75282"
yellow = "#af8f01"
orange = "#c9663c"
green = "#09957f"
cyan = "#0e919a"
blue = "#7061bd"
magenta = "#a459a6"
brown = "#793d24"

bright_red = "#a23a6e"
bright_yellow = "#957b0f"
bright_green = "#077e6a"
bright_cyan = "#107a82"
bright_blue = "#5d4aaa"
bright_magenta = "#8f4292"
