mode = "light"

accent = "#4c5dd2"
selection = "#ced5f3"
muted = "#98a6b8"

background = "#f3f7fc"
dark_background = "#e3ecf7"
darker_background = "#d6dfea"
lighter_background = "#d9e4f3"

foreground = "#1b2737"
dark_foreground = "#677382"
light_foreground = "#3d4958"
bright_foreground = "#0a1421"

hyprland_active_border = "rgba(018589ee) rgba(4c5dd2ee) 45deg"
hyprland_inactive_border = "rgba(98a6b8aa)"

red = "#016d91"
yellow = "#1190dc"
orange = "#0d7fb3"
green = "#018090"
cyan = "#018589"
blue = "#2f58c8"
magenta = "#4c5dd2"
brown = "#084c6b"

bright_red = "#065775"
bright_yellow = "#0a7bbc"
bright_green = "#106976"
bright_cyan = "#006f72"
bright_blue = "#1b40b5"
bright_magenta = "#3a44bf"
