mode = "light"

accent = "#bf07a4"
selection = "#ebc2e5"
muted = "#aaa2a4"

background = "#f7f7f7"
dark_background = "#ebebeb"
darker_background = "#dedede"
lighter_background = "#e3e3e3"

foreground = "#2b2426"
dark_foreground = "#776f71"
light_foreground = "#4d4647"
bright_foreground = "#181214"

hyprland_active_border = "rgba(04848fee) rgba(bf07a4ee) 45deg"
hyprland_inactive_border = "rgba(aaa2a4aa)"

red = "#d60203"
yellow = "#a18c0b"
orange = "#b46b09"
green = "#338b01"
cyan = "#04848f"
blue = "#193dff"
magenta = "#bf07a4"
brown = "#6c4005"

bright_red = "#b20404"
bright_yellow = "#89770b"
bright_green = "#287300"
bright_cyan = "#0f6d76"
bright_blue = "#1200ed"
bright_magenta = "#9f0488"
