mode = "light"

accent = "#9e37c8"
selection = "#e2cdf1"
muted = "#9da4b8"

background = "#f5f7fc"
dark_background = "#e5ebfb"
darker_background = "#d8deed"
lighter_background = "#dbe3f7"

foreground = "#1f253a"
dark_foreground = "#6b7184"
light_foreground = "#40475b"
bright_foreground = "#0f1321"

hyprland_active_border = "rgba(097eadee) rgba(9e37c8ee) 45deg"
hyprland_inactive_border = "rgba(9da4b8aa)"

red = "#d40336"
yellow = "#a78905"
orange = "#bd6400"
green = "#018589"
cyan = "#097ead"
blue = "#0e53dd"
magenta = "#9e37c8"
brown = "#713c00"

bright_red = "#b0042c"
bright_yellow = "#8e7503"
bright_green = "#0a6e71"
bright_cyan = "#056990"
bright_blue = "#003fbe"
bright_magenta = "#8a0db5"
