mode = "light"

accent = "#b105c9"
selection = "#e3c4e7"
muted = "#9baa98"

background = "#f1faef"
dark_background = "#e5eee3"
darker_background = "#d8e1d6"
lighter_background = "#dbe7d8"

foreground = "#1d2b1b"
dark_foreground = "#697666"
light_foreground = "#3f4c3d"
bright_foreground = "#0c170a"

hyprland_active_border = "rgba(008e1fee) rgba(b105c9ee) 45deg"
hyprland_inactive_border = "rgba(9baa98aa)"

red = "#518200"
yellow = "#909305"
orange = "#738a0a"
green = "#9429f4"
cyan = "#008e1f"
blue = "#007838"
magenta = "#b105c9"
brown = "#455306"

bright_red = "#436b05"
bright_yellow = "#7b7d07"
bright_green = "#7e02d6"
bright_cyan = "#07751b"
bright_blue = "#05602d"
bright_magenta = "#9300a8"
