mode = "light"

accent = "#c30496"
selection = "#f0c0df"
muted = "#b49f9e"

background = "#fdf5f4"
dark_background = "#f4e8e7"
darker_background = "#e7dbda"
lighter_background = "#efdfde"

foreground = "#332121"
dark_foreground = "#7f6c6c"
light_foreground = "#554342"
bright_foreground = "#1e0f0f"

hyprland_active_border = "rgba(028587ee) rgba(c30496ee) 45deg"
hyprland_inactive_border = "rgba(b49f9eaa)"

red = "#d40b1d"
yellow = "#a98804"
orange = "#ba6603"
green = "#088c42"
cyan = "#028587"
blue = "#0766ac"
magenta = "#c30496"
brown = "#703d02"

bright_red = "#b20114"
bright_yellow = "#907406"
bright_green = "#097436"
bright_cyan = "#0f6e6f"
bright_blue = "#00528e"
bright_magenta = "#a2037d"
