mode = "light"

accent = "#8869af"
selection = "#dad5ec"
muted = "#a1a3b4"

background = "#f1f3fd"
dark_background = "#e6e7f1"
darker_background = "#d9dae4"
lighter_background = "#dddfeb"

foreground = "#242534"
dark_foreground = "#6e707f"
light_foreground = "#454655"
bright_foreground = "#11131f"

hyprland_active_border = "rgba(0d9299ee) rgba(8869afee) 45deg"
hyprland_inactive_border = "rgba(a1a3b4aa)"

red = "#a35f92"
yellow = "#ad8e38"
orange = "#bf6b5a"
green = "#2f956e"
cyan = "#0d9299"
blue = "#5c6cb2"
magenta = "#8869af"
brown = "#734036"

bright_red = "#8f497e"
bright_yellow = "#997912"
bright_green = "#0a7f5a"
bright_cyan = "#007b82"
bright_blue = "#48579e"
bright_magenta = "#74539c"
