mode = "light"

accent = "#b43854"
selection = "#edcbcc"
muted = "#b0a295"

background = "#fdf5ee"
dark_background = "#f2eae2"
darker_background = "#e5dcd5"
lighter_background = "#ebe1d7"

foreground = "#302418"
dark_foreground = "#7c6f64"
light_foreground = "#51453a"
bright_foreground = "#1c1108"

hyprland_active_border = "rgba(a06603ee) rgba(b43854ee) 45deg"
hyprland_inactive_border = "rgba(b0a295aa)"

red = "#ac3229"
yellow = "#b17f00"
orange = "#b35b02"
green = "#8e6c09"
cyan = "#a06603"
blue = "#a63d03"
magenta = "#b43854"
brown = "#6b3701"

bright_red = "#970e0d"
bright_yellow = "#966c09"
bright_green = "#765901"
bright_cyan = "#855407"
bright_blue = "#863003"
bright_magenta = "#9f1840"
