mode = "light"

accent = "#c50657"
selection = "#ecc2d4"
muted = "#aaa2a4"

background = "#f7f7f7"
dark_background = "#ebebeb"
darker_background = "#dedede"
lighter_background = "#e3e3e3"

foreground = "#2b2426"
dark_foreground = "#776f71"
light_foreground = "#4d4647"
bright_foreground = "#181214"

hyprland_active_border = "rgba(bf4a00ee) rgba(c50657ee) 45deg"
hyprland_inactive_border = "rgba(aaa2a4aa)"

red = "#bb061f"
yellow = "#c96e00"
orange = "#c34903"
green = "#d41004"
cyan = "#bf4a00"
blue = "#ba0426"
magenta = "#c50657"
brown = "#752c02"

bright_red = "#990015"
bright_yellow = "#ab5e05"
bright_green = "#b20300"
bright_cyan = "#9e3e06"
bright_blue = "#98041e"
bright_magenta = "#a40046"
