mode = "light"

accent = "#b203c8"
selection = "#e5c1f1"
muted = "#9aa5b8"

background = "#f4f7fc"
dark_background = "#e4ecf8"
darker_background = "#d7deea"
lighter_background = "#dae4f3"

foreground = "#1d2737"
dark_foreground = "#687282"
light_foreground = "#3e4858"
bright_foreground = "#0c1421"

hyprland_active_border = "rgba(068683ee) rgba(b203c8ee) 45deg"
hyprland_inactive_border = "rgba(9aa5b8aa)"

red = "#8b1cfe"
yellow = "#0c98ce"
orange = "#4072f8"
green = "#0e8395"
cyan = "#068683"
blue = "#004deb"
magenta = "#b203c8"
brown = "#264495"

bright_red = "#7401d9"
bright_yellow = "#0c82b0"
bright_green = "#026d7d"
bright_cyan = "#116f6c"
bright_blue = "#003cc3"
bright_magenta = "#9305a6"
