mode = "light"

accent = "#6e5bce"
selection = "#d6d5f2"
muted = "#98a6b8"

background = "#f3f7fc"
dark_background = "#e3ecf7"
darker_background = "#d6dfea"
lighter_background = "#d9e4f3"

foreground = "#1b2737"
dark_foreground = "#677382"
light_foreground = "#3d4958"
bright_foreground = "#0a1421"

hyprland_active_border = "rgba(0d8395ee) rgba(6e5bceee) 45deg"
hyprland_inactive_border = "rgba(98a6b8aa)"

red = "#bf3955"
yellow = "#b18406"
orange = "#c35d19"
green = "#058684"
cyan = "#0d8395"
blue = "#145fc1"
magenta = "#6e5bce"
brown = "#75380f"

bright_red = "#aa1740"
bright_yellow = "#96710c"
bright_green = "#026f6d"
bright_cyan = "#086d7c"
bright_blue = "#004aa4"
bright_magenta = "#5b44bb"
