mode = "light"

accent = "#be00a9"
selection = "#eac1e6"
muted = "#aaa2a4"

background = "#f7f7f7"
dark_background = "#ebebeb"
darker_background = "#dedede"
lighter_background = "#e3e3e3"

foreground = "#2b2426"
dark_foreground = "#776f71"
light_foreground = "#4d4647"
bright_foreground = "#181214"

hyprland_active_border = "rgba(01858aee) rgba(be00a9ee) 45deg"
hyprland_inactive_border = "rgba(aaa2a4aa)"

red = "#d60015"
yellow = "#a18c0b"
orange = "#b56a0d"
green = "#0a8d2b"
cyan = "#01858a"
blue = "#015dca"
magenta = "#be00a9"
brown = "#6d4008"

bright_red = "#b20010"
bright_yellow = "#8a7707"
bright_green = "#017521"
bright_cyan = "#0a6e72"
bright_blue = "#004aa5"
bright_magenta = "#9d058c"
