mode = "light"

accent = "#944eb0"
selection = "#e1d2e7"
muted = "#aaa2a4"

background = "#f7f7f7"
dark_background = "#ebebeb"
darker_background = "#dedede"
lighter_background = "#e3e3e3"

foreground = "#2b2426"
dark_foreground = "#776f71"
light_foreground = "#4d4647"
bright_foreground = "#181214"

hyprland_active_border = "rgba(018589ee) rgba(944eb0ee) 45deg"
hyprland_inactive_border = "rgba(aaa2a4aa)"

red = "#bd423c"
yellow = "#a38b08"
orange = "#b7690a"
green = "#0a8c37"
cyan = "#018589"
blue = "#265ebc"
magenta = "#944eb0"
brown = "#6e3f06"

bright_red = "#a82424"
bright_yellow = "#8c7600"
bright_green = "#00752b"
bright_cyan = "#016e72"
bright_blue = "#0948aa"
bright_magenta = "#80369c"
