mode = "light"

accent = "#9762a8"
selection = "#dfd2ea"
muted = "#a4a2b4"

background = "#f3f2fc"
dark_background = "#e7e6f1"
darker_background = "#dad9e3"
lighter_background = "#dfdeeb"

foreground = "#262433"
dark_foreground = "#716f7f"
light_foreground = "#474655"
bright_foreground = "#14121e"

hyprland_active_border = "rgba(0090a5ee) rgba(9762a8ee) 45deg"
hyprland_inactive_border = "rgba(a4a2b4aa)"

red = "#ae5a83"
yellow = "#b8892c"
orange = "#c36952"
green = "#039679"
cyan = "#0090a5"
blue = "#5b6bb7"
magenta = "#9762a8"
brown = "#753f31"

bright_red = "#9a436f"
bright_yellow = "#a27404"
bright_green = "#057e66"
bright_cyan = "#08798b"
bright_blue = "#4756a4"
bright_magenta = "#834c94"
