mode = "light"

accent = "#bd03ab"
selection = "#e9c1ed"
muted = "#a0a3b8"

background = "#f5f6ff"
dark_background = "#e8eafa"
darker_background = "#dbdded"
lighter_background = "#dfe1f6"

foreground = "#23243a"
dark_foreground = "#6e7083"
light_foreground = "#44465b"
bright_foreground = "#111221"

hyprland_active_border = "rgba(03848eee) rgba(bd03abee) 45deg"
hyprland_inactive_border = "rgba(a0a3b8aa)"

red = "#d40530"
yellow = "#a28c0a"
orange = "#ba6700"
green = "#088d1c"
cyan = "#03848e"
blue = "#4f25ff"
magenta = "#bd03ab"
brown = "#703e00"

bright_red = "#b00727"
bright_yellow = "#8a770a"
bright_green = "#007612"
bright_cyan = "#0f6d75"
bright_blue = "#4001db"
bright_magenta = "#9d008e"
