mode = "light"

accent = "#b01fbe"
selection = "#e7c7ea"
muted = "#aaa2a4"

background = "#f7f7f7"
dark_background = "#ebebeb"
darker_background = "#dedede"
lighter_background = "#e3e3e3"

foreground = "#2b2426"
dark_foreground = "#776f71"
light_foreground = "#4d4647"
bright_foreground = "#181214"

hyprland_active_border = "rgba(10867dee) rgba(b01fbeee) 45deg"
hyprland_inactive_border = "rgba(aaa2a4aa)"

red = "#d40922"
yellow = "#9b8f00"
orange = "#b46b05"
green = "#5f8209"
cyan = "#10867d"
blue = "#005ccc"
magenta = "#b01fbe"
brown = "#6c4003"

bright_red = "#b1061b"
bright_yellow = "#847a0c"
bright_green = "#4f6c07"
bright_cyan = "#0f6f68"
bright_blue = "#004aa6"
bright_magenta = "#9600a3"
