mode = "light"

accent = "#b903b5"
selection = "#edbeee"
muted = "#ad9fb1"

background = "#fcf3fe"
dark_background = "#f2e7f5"
darker_background = "#e5dae7"
lighter_background = "#ecddef"

foreground = "#2f2033"
dark_foreground = "#7a6c7d"
light_foreground = "#504254"
bright_foreground = "#1a0f1c"

hyprland_active_border = "rgba(02848dee) rgba(b903b5ee) 45deg"
hyprland_inactive_border = "rgba(ad9fb1aa)"

red = "#d00158"
yellow = "#a68a06"
orange = "#c45d00"
green = "#108a5d"
cyan = "#02848d"
blue = "#0765af"
magenta = "#b903b5"
brown = "#763800"

bright_red = "#ad0748"
bright_yellow = "#8e750b"
bright_green = "#00734c"
bright_cyan = "#006e76"
bright_blue = "#005190"
bright_magenta = "#9a0096"
